# Default values for podium.

redis:
  port: 6379
  volume:
    size: 1Gi
  backup:
    interval: 86400
    minKeysChange: 10

storage:
  s3:
    bucket: podium-expt
    baseKey: podium/storage

fuseki:
  configmap:
    name: default-fuseki-config
    key: config.ttl
  consumer:
    enabled: false

podium:
  service:
    name: podium
  worker:
    replicas: 1
    fuseki:
      dataset:
        text:
          # Note - if you enable this, you must also change the Fuseki config in worker/configmap.yaml.
          enabled: false
  volume:
    path: /var/podium
    size: 2Gi