language: generic
env:
  - HELM_VERSION=2.14.1 HELM_S3_VERSION=0.8.0
install: 
  - wget https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz
  - tar -xzf helm-v$HELM_VERSION-linux-amd64.tar.gz
  - cp linux-amd64/helm /usr/local/bin/helm
  - helm plugin install https://github.com/hypnoglow/helm-s3.git --version $HELM_S3_VERSION
script: make build
deploy:
  skip_cleanup: true
  script: make deploy
  on:
    branch: master


