apiVersion: v1
kind: Pod
metadata:
  labels:
    app: podium-manager
  name: manager
spec:
  containers:
  - image: 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/podium-manager-web:{{ .Chart.AppVersion }}
    name: manager
    env:
    - name: PODIUM_SERVICE_NAME
      value: {{ .Values.podium.service.name }}
    - name: SPRING_REDIS_HOST
      value: redis
    - name: SPRING_REDIS_PORT
      value: "{{ .Values.redis.port }}"
    - name: STORAGE_S3_BUCKET
      value: {{ .Values.storage.s3.bucket }}
    - name: STORAGE_S3_BASEKEY
      value: {{ .Values.storage.s3.baseKey }}
    - name: PODIUM_WORKER_CLIENT_API
      value: http://worker:8080