apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd-cluster.fullname" . }}
  labels:
{{ include "fluentd-cluster.labels" . | indent 4 }}
data:
  fluent.conf: |
{{ .Values.fluentd.config | indent 4 }}

