---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd-cluster.fullname" . }}
  labels:
{{ include "fluentd-cluster.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "fluentd-cluster.fullname" . }}
  labels:
{{ include "fluentd-cluster.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "fluentd-cluster.fullname" . }}
  labels:
{{ include "fluentd-cluster.labels" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd-cluster.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "fluentd-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
