apiVersion: v1
kind: Pod
metadata:
  labels:
    app: podium-publisher
  name: podium-publisher
spec:
  containers:
  - image: 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/podium-publisher-web:{{ .Chart.AppVersion }}
    name: publisher
    env:
    - name: PODIUM_SERVICE_NAME
      value: {{ .Values.podium.service.name }}
    - name: SPRING_REDIS_HOST
      value: podium-redis-svc
    - name: SPRING_REDIS_PORT
      value: "{{ .Values.redis.port }}"
    - name: STORAGE_S3_BUCKET
      value: {{ .Values.storage.s3.bucket }}
    - name: STORAGE_S3_BASEKEY
      value: {{ .Values.storage.s3.baseKey }}
  {{ if .Values.aws }}
  {{ if .Values.aws.serviceAccount  }}
  serviceAccountName: {{ .Values.aws.serviceAccount }}
  {{ end }}
  {{ end }}
  {{ if and .Values.podium .Values.podium.publisher }}
  {{ if .Values.podium.publisher.nodeSelector  }}
  nodeSelector:
    {{- range $key, $value := .Values.podium.publisher.nodeSelector }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{ end }}
  {{ end }}