apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sapi-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sapi-app.name" . }}
    helm.sh/chart: {{ include "sapi-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    skipper: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sapi-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sapi-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- include "prometheus.podAnnotations" . | nindent 8}}
    spec:
      {{- if .Values.logging.fluentd.enabled }}
      volumes:
      {{- include "fluentd.emptydir" . | nindent 6}}
      {{- end }}
      containers:
        {{- include "fluentd.sidecar" . | nindent 8}}
        {{- include "prometheus.sidecar" . | nindent 8}}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.logging.fluentd.enabled }}
          volumeMounts:
          {{- include "fluentd.logmount" . | nindent 10}}
          {{ end }}
          env:
          - name: RAILS_SAPI_API_BASE
            value: "http://{{ .Release.Name }}-sapi-api:8080"
          {{- include "fluentd.railsenv" . | nindent 10 -}}
          {{- include "prometheus.railsenv" . | nindent 10 -}}
{{- range .Values.environment }}
          - name: {{ .name }}
            value: {{ .value }}
{{- end }}
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-rails-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- if .Values.metrics.prometheus.serviceMonitor.enabled }}
            - name: prometheus
              containerPort: 9394
              protocol: TCP
{{- end }}
        {{ if .Values.probes.livenessProbe }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
        {{ end }}
        {{ if .Values.probes.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
        {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
