{{- if .Values.logging.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sapi-app.fullname" . }}-logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      @label @raw
    </source>

    <label @raw>
      <filter>
        @type parser
        format /^(?<other>([^\n]+\n)*)?(?<jsondata>{(.*)})$/
        reserve_data true
        key_name messages
      </filter>
      <filter>
        @type record_transformer
        remove_keys jsondata
        <record>
          messages ${record["jsondata"]}
        </record>
      </filter>
      <match>
        @type copy
        <store>
          @type relabel
          @label @cleaned
        </store>
        <store>
          @type relabel
          @label @other
        </store>
      </match>
    </label>

    <label @other>
      <filter>
        @type parser
        key_name other
        ignore_key_not_exist true
        <parse>
          @type none
        </parse>
      </filter>
      <match>
        @type stdout
        format single_value
      </match>
    </label>

    <label @cleaned>
      <filter>
        @type parser
        key_name messages
        <parse>
          @type json
        </parse>
      </filter>
      <filter>
        @type record_transformer
        <record>
          time ${time}
          tag ${tag}
        </record>
      </filter>
      <match>
        @type relabel
        @label @rails
      </match>
    </label>
    <label @rails>
      <match>
        @type copy
        <store>
          @type stdout
          format json
        </store>
  {{- if default false .Values.logging.fluentd.s3.enabled }}
        <store>
          @type s3
          format json

          aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
          aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
          s3_bucket "#{ENV['S3_BUCKET']}"
          s3_region "#{ENV['AWS_REGION']}"
          path "#{ENV['S3_PATH']}"

          <buffer tag,time>
            @type file
            path /var/log/s3
            flush_at_shutdown true
            timekey 3600 # 1 hour partition
            timekey_wait 10m
            timekey_use_utc true # use utc
            chunk_limit_size 256m
          </buffer>
        </store>
  {{- end}}
      </match>
    </label>
{{- end }}
