apiVersion: v1
kind: Service
metadata:
  name: {{ include "sapi-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sapi-app.name" . }}
    helm.sh/chart: {{ include "sapi-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    skipper.epimorphics.com/visibility: "true"
    skipper.epimorphics.com/stage: {{ .Values.skipper.stage }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.metrics.prometheus.serviceMonitor.enabled }}
    - port: 9394
      targetPort: prometheus
      protocol: TCP
      name: prometheus
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "sapi-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
