{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fuseki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fuseki.name" . }}
    helm.sh/chart: {{ include "fuseki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpoints:
  - path: /$/metrics
    port: fuseki
  namespaceSelector:
    matchNames:
    - {{ .Release.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fuseki.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
