apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: {{ .Values.redis.port }}
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  nodeSelector:
    role: cassandra
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-data
    - name: config
      configMap:
        name: redis-config
        items:
          - key: redis.conf
            path: redis.conf