apiVersion: v1
kind: Pod
metadata:
  labels:
    app: podium-redis
  name: podium-redis
spec:
  containers:
    - name: redis
      image: redis
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: {{ .Values.redis.port }}
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      {{ if .Values.redis.volume.class }}
      persistentVolumeClaim:
        claimName: redis-data
      {{ else }}
      emptyDir: {}
      {{ end }}
    - name: config
      configMap:
        name: redis-config
        items:
          - key: redis.conf
            path: redis.conf
  {{ if and .Values.redis .Values.redis.nodeSelector }}
  nodeSelector:
    {{- range $key, $value := .Values.redis.nodeSelector }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{ end }}