{{ if .Values.redis.volume.class }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podium-redis-data
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.volume.class }}
  resources:
    requests:
      storage: {{ .Values.redis.volume.size }}
{{ end }}