apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes: 
    - ReadWriteOnce
  {{ if .Values.redis.volume.class  }}
  storageClassName: {{ .Values.redis.volume.class }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.redis.volume.size }}