apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app: redis
