apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: podium-worker
spec:
  type: ClusterIP
  selector:
    app: podium-worker
  ports:
    - name: manager
      port: 8080
      targetPort: 8080
    - name: fuseki
      port: 3030
      targetPort: 3030
