apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: worker
  replicas: {{ .Values.podium.worker.replicas }}
  selector:
    matchLabels:
      app: podium-worker
  template:
    metadata:
      labels:
        app: podium-worker
    spec:
      initContainers:
      - image: 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/podium-worker-init-app:{{ .Chart.AppVersion }}
        name: init
        env:
        - name: PODIUM_SERVICE_NAME
          value: {{ .Values.podium.service.name }}
        - name: SPRING_REDIS_HOST
          value: redis
        - name: SPRING_REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: STORAGE_S3_BUCKET
          value: {{ .Values.storage.s3.bucket }}
        - name: STORAGE_S3_BASEKEY
          value: {{ .Values.storage.s3.baseKey }}
        - name: FUSEKI_BASE
          value: {{ .Values.podium.volume.path }}/fuseki
        - name: PODIUM_WORKER_FUSEKI_DATASET_TEXT_ENABLED 
          value: "{{ .Values.podium.worker.fuseki.dataset.text.enabled }}"
        - name: PODIUM_WORKER_BASEPATH
          value: {{ .Values.podium.volume.path }}
        volumeMounts:
        - name: worker-data
          mountPath: "{{ .Values.podium.volume.path }}"
        - name: fuseki-config
          mountPath: "{{ .Values.podium.volume.path }}/fuseki/config.ttl"
          subPath: "config.ttl"
      containers:
      - image: 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/managed-fuseki:3.13.0
        name: fuseki
        env:
        - name: FUSEKI_BASE
          value: {{ .Values.podium.volume.path }}/fuseki
        volumeMounts:
        - name: worker-data
          mountPath: "{{ .Values.podium.volume.path }}"
        - name: fuseki-config
          mountPath: "{{ .Values.podium.volume.path }}/fuseki/config.ttl"
          subPath: "config.ttl"
        {{ if and .Values.fuseki.postgis .Values.fuseki.postgis.mountPath }}
        - name: pgpasswd
          mountPath: "{{ .Values.fuseki.postgis.mountPath }}"
          subPath: passwd
        {{ end }}
      - image: 293385631482.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/podium-worker-manager-web:{{ .Chart.AppVersion }}
        name: manager
        env:
        - name: PODIUM_SERVICE_NAME
          value: {{ .Values.podium.service.name }}
        - name: SPRING_REDIS_HOST
          value: redis
        - name: SPRING_REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: STORAGE_S3_BUCKET
          value: {{ .Values.storage.s3.bucket }}
        - name: STORAGE_S3_BASEKEY
          value: {{ .Values.storage.s3.baseKey }}
        - name: FUSEKI_BASE
          value: {{ .Values.podium.volume.path }}/fuseki
        - name: PODIUM_WORKER_FUSEKI_DATASET_TEXT_ENABLED 
          value: "{{ .Values.podium.worker.fuseki.dataset.text.enabled }}"
        - name: PODIUM_WORKER_BASEPATH
          value: {{ .Values.podium.volume.path }}
        - name: PODIUM_PUBLISH_CLIENT_API
          value: http://publisher:8080
        - name: PODIUM_WORKER_APIHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1
        volumeMounts:
        - name: worker-data
          mountPath: "{{ .Values.podium.volume.path }}"
        - name: fuseki-config
          mountPath: "{{ .Values.podium.volume.path }}/fuseki/config.ttl"
          subPath: "config.ttl"
      {{ if .Values.aws }}
      {{ if .Values.aws.serviceAccount  }}
      serviceAccountName: {{ .Values.aws.serviceAccount }}
      {{ end }}
      {{ end }}
      {{ if and .Values.podium .Values.podium.worker }}
      {{ if .Values.podium.worker.nodeSelector  }}
      nodeSelector:
        {{- range $key, $value := .Values.podium.worker.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{ end }}
      {{ end }}
      volumes:
        - name: fuseki-config
          configMap:
            name: {{ .Values.fuseki.configmap.name }}
            items:
            - key: "{{ .Values.fuseki.configmap.key }}"
              path: "config.ttl"
        {{ if and .Values.fuseki.postgis .Values.fuseki.postgis.secretName }}
        - name: pgpasswd
          secret:
            secretName: {{ .Values.fuseki.postgis.secretName }}
            items:
            - key: {{ .Values.fuseki.postgis.pwdKey }}
              path: passwd
        {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: worker-data
    spec:
      accessModes: 
        - ReadWriteOnce
      {{ if .Values.podium.volume.class  }}
      storageClassName: {{ .Values.podium.volume.class }}
      {{ end }}
      resources:
        requests:
          storage: {{ .Values.podium.volume.size }}