apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sapi-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sapi-api.name" . }}
    helm.sh/chart: {{ include "sapi-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sapi-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sapi-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        {{- include "sapi-api.cache-nginx" . | indent 8 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SERVER_PORT
            value: "{{ .Values.app.port }}"
          - name: SERVER_DATASOURCE_ENDPOINT
{{- if .Values.fuseki.inRelease }}
            value: "http://{{ .Release.Name }}-fuseki:3030/ds/query"
{{- else }}
            value: "{{ .Values.fuseki.location }}"
{{- end }}
{{- range .Values.environment }}
          - name: {{ .name }}
            value: {{ .value }}
{{- end }}
          envFrom:
{{- range .Values.secrets }}
          - secretRef:
              name: {{ .name }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if "Values.cache.enabled" }}
      volumes:
      {{- include "sapi-api.cache-nginx-volume" . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
