apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-proxy.name" . }}
    helm.sh/chart: {{ include "nginx-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nifi.conf: |
  {{- .Values.config | nindent 4 }}
